import type { TierEntry } from '../types/classes';

export const TIER_DATA: TierEntry[] = [
  {
    tier: 'S+',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Ball Lightning (Ballkuna)',
    classSlug: 'sorcerer',
    className: 'Sorcerer',
    playstyle: 'Shock AoE / Screen clear',
  },
  {
    tier: 'S+',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Death Trap',
    classSlug: 'rogue',
    className: 'Rogue',
    playstyle: 'Trap burst / AoE nuke',
  },
  {
    tier: 'S',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Whirlwind',
    classSlug: 'barbarian',
    className: 'Barbarian',
    playstyle: 'Spin-to-win / Dust Devils',
  },
  {
    tier: 'S',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Static Field Blizzard (Shockuna)',
    classSlug: 'sorcerer',
    className: 'Sorcerer',
    playstyle: 'Lightning DoT / Unstable Currents',
  },
  {
    tier: 'S',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Dance of Knives',
    classSlug: 'rogue',
    className: 'Rogue',
    playstyle: 'Channel spin / Fan of Knives',
  },
  {
    tier: 'S',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Apocalypse Warlock',
    classSlug: 'warlock',
    className: 'Warlock',
    playstyle: 'Hellfire nuke / 100-stack ramp',
  },
  {
    tier: 'S',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Dread Claws',
    classSlug: 'warlock',
    className: 'Warlock',
    playstyle: 'Shadow AoE / Stealth positioning',
  },
  {
    tier: 'S',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Ancient Leap / HotA',
    classSlug: 'barbarian',
    className: 'Barbarian',
    playstyle: 'Fire melee / Summoner hybrid',
  },
  {
    tier: 'S',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Auradin (Holy Light Aura)',
    classSlug: 'paladin',
    className: 'Paladin',
    playstyle: 'Aura walk-through / Zero button',
  },
  {
    tier: 'S',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Blessed Hammer (Hammerdin)',
    classSlug: 'paladin',
    className: 'Paladin',
    playstyle: 'Orbiting hammers / Arbiter form',
  },
  {
    tier: 'S',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Blazing Abyss',
    classSlug: 'warlock',
    className: 'Warlock',
    playstyle: 'Permanent stealth / Abyss pulses',
  },
  {
    tier: 'S',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Pulverize',
    classSlug: 'druid',
    className: 'Druid',
    playstyle: 'Werebear slam / Overpower',
  },
  {
    tier: 'S',
    tierColor: 'var(--gold-bright)',
    tierWeight: 900,
    build: 'Rabies Lacerate',
    classSlug: 'druid',
    className: 'Druid',
    playstyle: 'Poison DoT / Werewolf spread',
  },
  {
    tier: 'A',
    tierColor: '#8bc4e0',
    tierWeight: 700,
    build: 'Wing Strike · Thorns · Fist of Heavens · Zeal · Blessed Shield',
    classSlug: 'paladin',
    className: 'Paladin',
    playstyle: 'Multiple viable archetypes',
  },
  {
    tier: 'A',
    tierColor: '#8bc4e0',
    tierWeight: 700,
    build: 'Rapid Fire · Penetrating Shot · Barrage · Flurry',
    classSlug: 'rogue',
    className: 'Rogue',
    playstyle: 'Ranged bow / Freeze-Shatter',
  },
  {
    tier: 'A',
    tierColor: '#8bc4e0',
    tierWeight: 700,
    build: "Abaddon Summoner · Blazing Scream · Tyrant's Grasp",
    classSlug: 'warlock',
    className: 'Warlock',
    playstyle: 'Demon army / Hellfire / Demonform',
  },
  {
    tier: 'A',
    tierColor: '#8bc4e0',
    tierWeight: 700,
    build: 'Hydra · Crackling Energy · Blizzard',
    classSlug: 'sorcerer',
    className: 'Sorcerer',
    playstyle: 'Summon caster / Shock / Frost',
  },
  {
    tier: 'A',
    tierColor: '#8bc4e0',
    tierWeight: 700,
    build: 'Shadowblight · Blood Wave · Summoner Zerg',
    classSlug: 'necromancer',
    className: 'Necromancer',
    playstyle: 'Shadow DoT / Blood AoE / Minion army',
  },
  {
    tier: 'A',
    tierColor: '#8bc4e0',
    tierWeight: 700,
    build: 'Wolf Companion · Cataclysm · Stormslide · Tornado',
    classSlug: 'druid',
    className: 'Druid',
    playstyle: 'Pet / Storm / Hybrid',
  },
  {
    tier: 'A',
    tierColor: '#8bc4e0',
    tierWeight: 700,
    build: 'Evade Eagle · Quill Volley · Payback',
    classSlug: 'spiritborn',
    className: 'Spiritborn',
    playstyle: 'Evade spam / Feather barrage / Counter',
  },
  {
    tier: 'B',
    tierColor: '#a0a0a0',
    tierWeight: 400,
    build:
      'Tornado, Shred, Boulder, Lightning Storm, Hurricane, Werenado, Bone Spirit, Blood Lance, Army of Dead, Fireball, Frozen Orb, Twisting Blades, Heartseeker, Lunging Strike, Cleave, Spear of Heavens, Heaven\'s Fury, Sever',
    classSlug: 'druid', // placeholder — B-tier row spans all classes
    className: '',
    playstyle: '',
    isBTier: true,
  },
];

export { TIER_DATA as tierData };
